**❓ What is Pandas**

Pandas is a Python library used for loading, cleaning, and analyzing data. It provides easy to use tools like Series and DataFrames for working with structured datasets.

**⚙️ Why Pandas is Important in Machine Learning**

Pandas is the **go-to library for data manipulation and analysis** in Machine Learning.  
It is built on top of NumPy and provides easy-to-use data structures like **Series** and **DataFrame**.

**🔍 Why Pandas is Essential:**
- 📂 **Data Handling:** Load, clean, and preprocess real-world datasets (CSV, Excel, SQL, JSON).
- 🧭 **Data Exploration:** Understand your data — structure, missing values, correlations.
- ⚙️ **Integration with ML:** Works seamlessly with Scikit-Learn, NumPy, Matplotlib, and Seaborn.
- 📈 **Feature Engineering:** Create, transform, and select useful features for models.
- 🔢 **Efficient Operations:** Built on NumPy, so it’s fast and memory-efficient.

> 💡 *Pandas turns messy, raw data into clean, model-ready data.*

---

In [1]:
%pip install -U -q pandas

Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

**Series(1D)**

In [3]:
s = pd.Series([1, 2, 3, 4, 5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
print("Element at index 0:", s[0])  # Output: 1
print("Elements from index 1 to 3:", s[1:4])  # Output: 2, 3, 4
print("Mean:", s.mean())  # Output: 3.0
print("Sum:", s.sum())   # Output: 15
print("Description:\n", s.describe())  # Output: count, mean, std, min, 25%, 50%, 75%, max

Element at index 0: 1
Elements from index 1 to 3: 1    2
2    3
3    4
dtype: int64
Mean: 3.0
Sum: 15
Description:
 count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

In [6]:
print("Elements from index 1 to 3:", s[1:4])  # Output: 2, 3, 4

Elements from index 1 to 3: 1    2
2    3
3    4
dtype: int64

**DataFrame(2D data)**

In [7]:
data = {
    "Name": ['Alice', 'Bob', 'Charlie', 'David'],
    "Age": [24, 27, 22, 32],
    "Score": [85, 91, 78, 88]
}

data_frame = pd.DataFrame(data)

**DataFrame Explanation**

A DataFrame in pandas is a 2D labeled table of data, like a spreadsheet or SQL table. It has rows and columns, and each column can store a different data type.

In this notebook, the variable named `data_frame` is a DataFrame created from the dictionary with `Name`, `Age`, and `Score` columns.

If you want, I can also show how to print, inspect, or filter that DataFrame.

In [8]:
print(data_frame)

      Name  Age  Score
0    Alice   24     85
1      Bob   27     91
2  Charlie   22     78
3    David   32     88

In [9]:
print(data_frame.dtypes)

Name       str
Age      int64
Score    int64
dtype: object

In [10]:
print(type(data_frame))  # Output: <class 'pandas.core.series.Series'>

<class 'pandas.DataFrame'>

In [11]:
print(data_frame.head())  # Output: First 5 rows of the DataFrame

      Name  Age  Score
0    Alice   24     85
1      Bob   27     91
2  Charlie   22     78
3    David   32     88

In [27]:
# saving data frame to csv
data_frame.to_csv('data_frame.csv' , index=False)

**Read df from csv file**

In [19]:
diabetes_df = pd.read_csv('diabetes.csv')

In [21]:
diabetes_df.shape

(768, 9)

In [22]:
diabetes_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [23]:
diabetes_df.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [29]:
#read data_frame.csv and analyse it
df = pd.read_csv('data_frame.csv')

In [30]:
df.shape

(4, 3)

In [31]:
df.head()

      Name  Age  Score
0    Alice   24     85
1      Bob   27     91
2  Charlie   22     78
3    David   32     88

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   Score   4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

**Inspecting the data**

In [34]:
print("Shape of the DataFrame:", df.shape)
print("Data types of each column:\n", df.dtypes)
print("Column names:", df.columns)
print("Missing values in each column:\n", df.isnull().sum())

Shape of the DataFrame: (4, 3)
Data types of each column:
 Name       str
Age      int64
Score    int64
dtype: object
Column names: Index(['Name', 'Age', 'Score'], dtype='str')
Missing values in each column:
 Name     0
Age      0
Score    0
dtype: int64

In [35]:
#single column
print(df['Name'])

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: str

In [37]:
#multiple columns
print(df[['Name', 'Age', 'Score']])

      Name  Age  Score
0    Alice   24     85
1      Bob   27     91
2  Charlie   22     78
3    David   32     88

In [41]:
# row selection
print(df.iloc[0])  # First row
print(df.iloc[1:3])  # Rows from index 1 to 2
print(df.loc[df['Age'] > 25])  # Rows where Age is greater than 25

Name     Alice
Age         24
Score       85
Name: 0, dtype: object
      Name  Age  Score
1      Bob   27     91
2  Charlie   22     78
    Name  Age  Score
1    Bob   27     91
3  David   32     88

In [42]:
upper_age =df[df['Age'] > 25]
print(upper_age)

    Name  Age  Score
1    Bob   27     91
3  David   32     88

**adding new column**

In [43]:
df["eligible"] = df['Age'] > 24
print(df)

      Name  Age  Score  eligible
0    Alice   24     85     False
1      Bob   27     91      True
2  Charlie   22     78     False
3    David   32     88      True

**descriptive Statistics**

In [45]:
print("Average age:", df['Age'].mean())
print("Maximum age:", df['Age'].max())
print("Minimum age:", df['Age'].min())
print("Description:\n", df.describe())

Average age: 26.25
Maximum age: 32
Minimum age: 22
Description:
              Age      Score
count   4.000000   4.000000
mean   26.250000  85.500000
std     4.349329   5.567764
min    22.000000  78.000000
25%    23.500000  83.250000
50%    25.500000  86.500000
75%    28.250000  88.750000
max    32.000000  91.000000

**Handling missing data**

In [46]:
df2 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', None],
    'Age': [24, None, 22, 32],
    'Score': [85, 91, None, 88]
})

In [47]:
df2.head()

      Name   Age  Score
0    Alice  24.0   85.0
1      Bob   NaN   91.0
2  Charlie  22.0    NaN
3      NaN  32.0   88.0

In [48]:
df2.dropna(subset=['Name'], inplace=True)

In [49]:
df2.head()

      Name   Age  Score
0    Alice  24.0   85.0
1      Bob   NaN   91.0
2  Charlie  22.0    NaN

In [50]:
df2.dropna(subset=["Name"], inplace=True)

In [52]:
df2.head(5)

      Name   Age  Score
0    Alice  24.0   85.0
1      Bob   NaN   91.0
2  Charlie  22.0    NaN

In [53]:
df2["Age"] = df2["Age"].fillna(df2["Age"].mean())
df2["Score"] = df2["Score"].fillna(df2["Score"].mean())

In [54]:
df2.head()

      Name   Age  Score
0    Alice  24.0   85.0
1      Bob  23.0   91.0
2  Charlie  22.0   88.0