In [39]:
company_dict = {
    'id':[1,2,3,4,5],
    'company':["google","apple","meta","claude","xxx"]
}

In [40]:
company_dict

{'id': [1, 2, 3, 4, 5],
 'company': ['google', 'apple', 'meta', 'claude', 'xxx']}

In [41]:
company_dict['id']

[1, 2, 3, 4, 5]

In [42]:
company_dict['company']

['google', 'apple', 'meta', 'claude', 'xxx']

In [43]:
import pandas as pd

In [44]:
company_df = pd.DataFrame(company_dict) # Create a DataFrame from the company_dict dictionary to organize the data into a tabular format for analysis and manipulation
company_df # Display the company_df DataFrame to verify that it has been created correctly and to inspect its contents

   id company
0   1  google
1   2   apple
2   3    meta
3   4  claude
4   5     xxx

In [45]:
region_dict ={
    'id':[1,2,3,4],
    'region':['north','south','east','west']
}

In [46]:
region_df = pd.DataFrame(region_dict) # Create a DataFrame from the region_dict dictionary to organize the data into a tabular format for analysis and manipulation
region_df # Display the region_df DataFrame to verify that it has been created correctly and to

   id region
0   1  north
1   2  south
2   3   east
3   4   west

In [47]:

merged_df = company_df.merge(region_df, on='id') # Merge the company_df and region_df DataFrames based on the 'id' column to combine the information from both DataFrames into a single DataFrame called merged_df
merged_df

   id company region
0   1  google  north
1   2   apple  south
2   3    meta   east
3   4  claude   west

In [ ]:
def output_all_odd(x_list):
    all_odd_numbers = range(1,list.max(x_list)+1,2) # Generate a range of odd numbers starting from 1 up to the maximum value in x_list, with a step of 2 to ensure only odd numbers are included
    for i in x_list: # Iterate through each element i in the input list x_list
        y_list = []
        if i in all_odd_numbers: # Check if the current element i is present in the list of all odd numbers
            y.list.append(i) # If it is an odd number, append it to the y_list
            
    return y_list # Return the list of odd numbers found in x_list

In [49]:
def output_all_odd(x_list):
    if not x_list:
        return []
    all_odd_numbers = range(1, max(x_list) + 1, 2) # Generate a range of odd numbers starting from 1 up to the maximum value in x_list, with a step of 2 to ensure only odd numbers are included
    y_list = []
    for i in x_list:
        if i in all_odd_numbers:
            y_list.append(i)
    return y_list


output_all_odd([1, 2, 6, 4, 5, 6, 7, 8, 13])

[1, 5, 7, 13]

In [ ]:
x_list = [1, 2, 6, 4, 5, 6, 7, 8, 13]
output_all_odd(x_list)

In [51]:
output_all_odd = lambda x_list: [i for i in x_list if i % 2 == 1] if x_list else []

In [52]:
x_list = [1, 2, 6, 4, 5, 6, 7, 8, 13]
output_all_odd(x_list)

[1, 5, 7, 13]

In [53]:
is_even = lambda x: x % 2 == 0
is_even(3)

False

In [68]:
id = [1,2,3,4]

In [69]:
def converter(id):
  output = []
  try:
    for i in id:
      i=i+1
      output.append(i)
      
    return output
  except:
    print(i,"not a integer")

In [70]:
converter(id)

[2, 3, 4, 5]

In [71]:
def longest_palindrome(s):
    if not s:
        return ""
    
    start = end = 0

    def expand(left, right):
        while left >= 0 and right < len(s) and s[left] == s[right]:
            left -= 1
            right += 1
        return left + 1, right - 1

    for i in range(len(s)):
        l1, r1 = expand(i, i)
        l2, r2 = expand(i, i + 1)

        if r1 - l1 > end - start:
            start, end = l1, r1
        if r2 - l2 > end - start:
            start, end = l2, r2

    return s[start:end + 1]

# example
longest_palindrome("babad")

'bab'

In [72]:
# function to check if a substring 
# s[low..high] is a palindrome
def checkPal(str, low, high):
    while low < high:
        if str[low] != str[high]:
            return False
        low += 1
        high -= 1
    return True

# function to find the longest palindrome substring
def getLongestPal(s):
    
    n = len(s)

    # all substrings of length 1 are palindromes
    maxLen = 1
    start = 0

    # nested loop to mark start and end index
    for i in range(n):
        for j in range(i, n):

            # check if the current substring is 
            # a palindrome
            if checkPal(s, i, j) and (j - i + 1) > maxLen:
                start = i
                maxLen = j - i + 1

    return s[start:start + maxLen]

In [74]:
s = "forgeeksskeegfor"
print(getLongestPal(s))

geeksskeeg