** Load CSV, Excel and Parquet Files**

Load three common dataset formats used in Machine Learning:

- CSV files

- Excel files

- Parquet files

openpyxl: needed for Excel files like .xlsx

pyarrow: needed for Parquet files like .parquet

In [1]:
# install the required libraries
%pip install -q pandas openpyxl pyarrow

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
import os
import pandas as pd

**Load the csv file**

In [4]:
df_csv = pd.read_csv("titanic.csv")

In [5]:
type(df_csv)

pandas.DataFrame

In [13]:
df_csv.shape

(891, 12)

In [6]:
df_csv.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [8]:
#pd.read_csv?

In [11]:
# load selected columns from csv file
df_csv_selected = pd.read_csv("titanic.csv", 
                              usecols=["PassengerId", "Survived", "Pclass","Fare"]
                              )

In [14]:
df_csv_selected.shape

(891, 4)

In [12]:
df_csv_selected.head()

   PassengerId  Survived  Pclass     Fare
0            1         0       3   7.2500
1            2         1       1  71.2833
2            3         1       3   7.9250
3            4         1       1  53.1000
4            5         0       3   8.0500

In [15]:
# load first N rows of csv file
df_csv_n_rows = pd.read_csv("titanic.csv", nrows=5) 
df_csv_n_rows.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

In [16]:
df_csv_n_rows.shape

(5, 12)

**Load excel file**

In [17]:
df_excel = pd.read_excel("titanic.xlsx")

In [18]:
df_excel.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [19]:
#load selected columns from excel file
df_excel_selected = pd.read_excel("titanic.xlsx",
                                 usecols=["PassengerId", "Survived", "Pclass","Fare"]
                                 )
df_excel_selected.head()

   PassengerId  Survived  Pclass     Fare
0            1         0       3   7.2500
1            2         1       1  71.2833
2            3         1       3   7.9250
3            4         1       1  53.1000
4            5         0       3   8.0500

In [20]:
# check sheet names
xls = pd.ExcelFile("titanic.xlsx")
print(xls.sheet_names)

['Sheet1']

In [21]:
df_excel_sheet = pd.read_excel("titanic.xlsx", sheet_name="Sheet1") # default is 0, so it will load the first sheet
df_excel_sheet.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

**3. Load the Parquet file**

In [22]:
df_parquet = pd.read_parquet("titanic.parquet")
df_parquet.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [23]:
#load selected columns from parquet file
df_parquet_selected = pd.read_parquet("titanic.parquet", 
                                      columns=["PassengerId", "Survived", "Pclass","Fare"])
df_parquet_selected.head()

   PassengerId  Survived  Pclass     Fare
0            1         0       3   7.2500
1            2         1       1  71.2833
2            3         1       3   7.9250
3            4         1       1  53.1000
4            5         0       3   8.0500

**Load the csv file with different separator**

In [25]:
df_tab = pd.read_csv("titanic_tab.csv", sep="\t") # default separator is comma, so we need to specify the separator as tab

df_tab.shape

(891, 12)

In [26]:
df_tab.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

**Compare file sizes**

In [27]:
# define a function to compare file sizes
def compare_file_sizes(path):
    size_bytes = os.path.getsize(path)
    size_kb = round(size_bytes / 1024, 2)
    size_mb = round(size_kb / 1024, 2)
    return size_bytes, size_kb, size_mb

for file in ["titanic.csv", "titanic.xlsx", "titanic.parquet"]:
    size_bytes, size_kb, size_mb = compare_file_sizes(file)
    print(f"{file}: {size_bytes} bytes, {size_kb} KB, {size_mb} MB")

titanic.csv: 60302 bytes, 58.89 KB, 0.06 MB
titanic.xlsx: 68829 bytes, 67.22 KB, 0.07 MB
titanic.parquet: 41399 bytes, 40.43 KB, 0.04 MB